package io.github.campione01.mineclientbridge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BoatTransferProgressTest {
    @Test void mountRequiresDispatchAndTwoLaterDistinctTicks() {var p=new BoatTransferProgress(true);assertNull(p.observe(100,true,true,true,true,false));p.dispatch(100);assertNull(p.observe(100,true,true,true,true,false));assertNull(p.observe(101,true,true,true,true,false));assertNull(p.observe(101,true,true,true,true,false));assertEquals("boat_mount_observed",p.observe(102,true,true,true,true,false));assertEquals(2,p.stableTicks());}
    @Test void missingObservationNeverAuthorizesAnotherUse() {var p=new BoatTransferProgress(true);p.dispatch(100);for(int i=101;i<300;i++)assertNull(p.observe(i,false,false,false,false,true));assertThrows(IllegalStateException.class,()->p.dispatch(300));assertFalse(p.sneak(301,true));}
    @Test void transientMembershipResetsConfirmation() {var p=new BoatTransferProgress(true);p.dispatch(100);assertNull(p.observe(101,true,true,true,true,false));assertNull(p.observe(102,false,false,false,false,true));assertNull(p.observe(103,true,true,true,true,false));assertEquals("boat_mount_observed",p.observe(104,true,true,true,true,false));}
    @Test void wrongVehicleOrDriverOrPassengersCannotSucceed() {for(boolean mount:new boolean[]{true,false}){var p=new BoatTransferProgress(mount);p.dispatch(100);assertEquals("vehicle_changed",p.observe(101,true,false,false,false,true));assertEquals("boat_driver_or_passengers_changed",p.observe(101,true,true,false,true,false));assertEquals("boat_driver_or_passengers_changed",p.observe(101,true,true,true,false,false));}}
    @Test void boundedSneakCountsGameTicksAndNeverRestarts() {var p=new BoatTransferProgress(false);for(int t=100;t<110;t++){assertTrue(p.sneak(t,true));assertTrue(p.sneak(t,true));}assertEquals(10,p.sneakTicks());assertEquals(100,p.dispatchTick());for(int t=110;t<200;t++)assertFalse(p.sneak(t,true));assertEquals(10,p.sneakTicks());}
    @Test void dismountRequiresBothSidesOfPassengerRelationship() {var p=new BoatTransferProgress(false);assertTrue(p.sneak(100,true));assertNull(p.observe(101,false,false,false,false,false));assertNull(p.observe(102,false,false,false,false,true));assertNull(p.observe(102,false,false,false,false,true));assertEquals("boat_dismount_observed",p.observe(103,false,false,false,false,true));}
    @Test void detachStopsSneakAndReattachmentNeverRepeatsIt() {var p=new BoatTransferProgress(false);assertTrue(p.sneak(100,true));assertFalse(p.sneak(101,false));assertFalse(p.sneak(102,true));assertEquals(1,p.sneakTicks());}
    @Test void observationAndInputClockRegressionFailClosed() {var p=new BoatTransferProgress(false);assertTrue(p.sneak(100,true));assertNull(p.observe(101,true,true,true,true,false));assertEquals("boat_transfer_tick_regressed",p.observe(100,false,false,false,false,true));assertFalse(p.sneak(99,true));assertFalse(p.sneak(102,true));}
    @Test void sameTickContradictionResetsStableEvidence() {var p=new BoatTransferProgress(false);p.sneak(100,true);assertNull(p.observe(101,false,false,false,false,true));assertNull(p.observe(101,true,true,true,true,false));assertNull(p.observe(102,false,false,false,false,true));assertEquals("boat_dismount_observed",p.observe(103,false,false,false,false,true));}
    @Test void regressionBeforeFirstPostDispatchSampleFails() {var p=new BoatTransferProgress(true);p.dispatch(105);assertEquals("boat_transfer_tick_regressed",p.observe(104,true,true,true,true,false));}
    @Test void observedDetachClosesLeaseBeforeSameTickReattachment() {var p=new BoatTransferProgress(false);assertTrue(p.sneak(100,true));assertNull(p.observe(101,false,false,false,false,true));assertFalse(p.sneak(101,true));assertFalse(p.sneak(102,true));assertEquals(1,p.sneakTicks());}
    @Test void preDispatchDetachCannotBeFollowedByALaterSneakAttempt() {var p=new BoatTransferProgress(false);assertNull(p.observe(100,false,false,false,false,true));assertFalse(p.sneak(101,true));assertFalse(p.dispatched());}
    @Test void noDismountSuccessBeforeActualInput() {var p=new BoatTransferProgress(false);assertNull(p.observe(101,false,false,false,false,true));assertNull(p.observe(102,false,false,false,false,true));assertFalse(p.dispatched());}
}
