package io.github.campione01.mineclientbridge;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class BoatDriveRequestTest {
 static JsonObject body() {return JsonParser.parseString("""
 {"action_id":"boat-a","action":"boat_drive","boat_schema_version":1,"timeout_ms":60000,
 "expected_world_generation":"00000000-0000-0000-0000-000000000001",
 "expected_player_uuid":"00000000-0000-0000-0000-000000000002",
 "expected_action_session":"00000000-0000-0000-0000-000000000003",
 "vehicle_uuid":"00000000-0000-0000-0000-000000000004","vehicle_entity_id":10,
 "vehicle_type":"minecraft:boat","water_surface_y":63,"waypoints":[{"x":0,"z":8},{"x":0,"z":16}]}
 """).getAsJsonObject();}
 @Test void validRequestHasExplicitIdentityAndImmutablePoints() {var r=BoatDriveRequest.parse(body());assertEquals(2,r.points().size());assertEquals(60000,r.timeoutMs());assertThrows(UnsupportedOperationException.class,()->r.points().clear());assertEquals("boat_drive",ClientActionRequest.parse(body()).action());}
 @Test void mandatoryIdentitiesAreCanonicalUuids() {for(String field:new String[]{"expected_world_generation","expected_player_uuid","expected_action_session","vehicle_uuid"}){var b=body();b.remove(field);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b));b.addProperty(field,"1-1-1-1-1");assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b));}}
 @Test void schemaRejectsUnknownNavigationOptionsAndUnsafeBypasses() {for(String field:new String[]{"append","renew","skip_safety","sprint","sneak","jump","hotbar_slot","priority","owner"}){var b=body();b.addProperty(field,true);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b),field);}}
 @Test void schemaRejectsTypesBoundsAndMissingRequiredValues() {for(String f:new String[]{"boat_schema_version","timeout_ms","vehicle_entity_id","water_surface_y"}){var b=body();b.addProperty(f,"1");assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b));}for(int n:new int[]{999,120001}){var b=body();b.addProperty("timeout_ms",n);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b));}}
 @Test void waypointsHaveOnlyFiniteXZAndBoundedCount() {var b=body();b.getAsJsonArray("waypoints").get(0).getAsJsonObject().addProperty("y",63);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b));var c=body();c.getAsJsonArray("waypoints").get(0).getAsJsonObject().addProperty("x",Double.NaN);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(c));var many=body();var p=many.getAsJsonArray("waypoints");for(int i=0;i<64;i++)p.add(p.get(0).deepCopy());assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(many));}
 @Test void rejectsLongSegmentAndTotalRouteAndNonBoat() {var b=body();b.getAsJsonArray("waypoints").get(1).getAsJsonObject().addProperty("z",30);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(b));var longRoute=body();var points=new JsonArray();for(int i=0;i<20;i++){var p=new JsonObject();p.addProperty("x",0);p.addProperty("z",i*16);points.add(p);}longRoute.add("waypoints",points);assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(longRoute));var chest=body();chest.addProperty("vehicle_type","minecraft:chest_boat");assertThrows(ClientActionRequest.Rejected.class,()->BoatDriveRequest.parse(chest));}
 @Test void repeatCannotReplayRenewOrAppendAfterLostResponse() {var registry=new ActionRegistry();var request=ClientActionRequest.parse(body());var entry=registry.begin(request);assertSame(entry,registry.begin(request));var changed=body();changed.addProperty("timeout_ms",70000);assertEquals("action_id_payload_mismatch",assertThrows(ClientActionRequest.Rejected.class,()->registry.begin(ClientActionRequest.parse(changed))).getMessage());var appended=body();appended.getAsJsonArray("waypoints").get(1).getAsJsonObject().addProperty("z",17);assertThrows(ClientActionRequest.Rejected.class,()->registry.begin(ClientActionRequest.parse(appended)));registry.finishAfterCleanup("cancelled","cancel_requested",true);assertSame(entry,registry.begin(request));assertNull(registry.active());assertEquals("cancelled",entry.status);}
 @Test void singleWriterRejectsConcurrentBoatAndCombatOrWalking() {var r=new ActionRegistry();r.begin(ClientActionRequest.parse(body()));var b=body();b.addProperty("action_id","different-writer");assertEquals("action_busy",assertThrows(ClientActionRequest.Rejected.class,()->r.begin(ClientActionRequest.parse(b))).getMessage());}
}
