package io.github.campione01.mineclientbridge;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
/** Source wiring assertions ONLY. They do not execute Minecraft or establish live safety. */
class BoatDriveContractTest {
 static String read(String file)throws Exception{return Files.readString(Path.of(System.getProperty("mineclientBridge.projectDir"),"src/main/java/io/github/campione01/mineclientbridge",file));}
 @Test void runtimeUsesBodyStateAndOrdinaryInputs()throws Exception{String b=read("BoundedBoatDrive.java");assertTrue(b.contains("boat.getYRot()"));assertTrue(b.contains("CollisionContext.of(boat)"));assertTrue(b.contains("hasChunkAt"));assertTrue(b.contains("boat.getPassengers()"));for(String x:new String[]{"setYRot(","setPos(","setDeltaMovement(","stopRiding(","startRiding(","look("})assertFalse(b.contains(x));}
 @Test void fixedDeadlineGuiDeathWorldAndCancelApplyToBoat()throws Exception{String a=read("ClientActions.java");assertTrue(a.contains("final long deadline"));assertTrue(a.contains("System.nanoTime() >= active.deadline"));assertTrue(a.contains("screen_opened"));assertTrue(a.contains("world_transition"));assertTrue(a.contains("player_unavailable"));assertTrue(a.contains("if (a.boat != null) released &= cleanup"));assertTrue(a.contains("input.left = a.left"));}
 @Test void cancellationNeverBrakesAndReportsInputSeparateFromSettlement()throws Exception{String b=read("BoundedBoatDrive.java");String release=b.substring(b.indexOf("void release("));assertTrue(release.contains("BoatInputRelease.clear(boat::setInput"));assertFalse(release.contains(".tick("));assertTrue(release.contains("input_released"));assertTrue(release.contains("boat_settled"));}
 @Test void noDynamicAppendOrRawHeldKeysOrTerrainReaderDependency()throws Exception{String b=read("BoundedBoatDrive.java");assertTrue(b.contains("dynamic_append_supported"));assertFalse(b.contains("TerrainReader"));assertFalse(b.contains("keyUp.setDown"));assertFalse(b.contains("keyUse"));}
 @Test void passengerGeometryUsesNativeAttachmentAndPoseDimensions()throws Exception{String b=read("BoundedBoatDrive.java");for(String x:new String[]{"getPassengerRidingPosition(passenger)","getVehicleAttachmentPoint(boat)","getDimensions(passenger.getPose()).makeBoundingBox(mount)","BoatPassengerEnvelope.inspect","passenger.getVehicle()==boat","passenger.isSpectator()","BoatPassengerEnvelope.membership","distinct().count()","passenger.getPassengers().size()"})assertTrue(b.contains(x),x);assertFalse(b.contains("passengerBox.minY<request.surfaceY()-.8"));}
 @Test void passengerEnvelopeCoversBothBlocksAndProtectedEntities()throws Exception{String b=read("BoundedBoatDrive.java");assertTrue(b.contains("clearanceHalfX+margin,clearanceHalfZ+margin"));assertTrue(b.contains("boat.getX()-clearanceHalfX,clearanceMinY"));assertTrue(b.contains("BoatCollision.protectedOverlap(box(body)"));assertTrue(b.contains("return \"passenger_geometry_unknown\""));}
 @Test void diagnosticsExposeObservedAndNativeExpectedBoxesSeparately()throws Exception{String b=read("BoatObservation.java");for(String x:new String[]{"passenger_geometry_schema_version","passenger_geometry","native_expected_aabb","native_mount_position","vehicle_attachment","native_width","native_height","geometry_complete","box(p.getBoundingBox())"})assertTrue(b.contains(x),x);}
}
